execution:
    uuid: 97e72cde-21c1-42b8-a40d-d4a7a21e943c
    runtime:
        start: 2023-06-05T14:10:03.463090-04:00
        end: 2023-06-06T04:34:43.973827-04:00
        duration: 14 hours, 24 minutes, 40 seconds, and 510737 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:fragment-insertion'
    action: sepp
    inputs:
    -   representative_sequences: 76a37ae0-6b6b-4758-a144-8a1b253fe4e7
    -   reference_database: a14c6180-506b-4ecb-bacb-9cb30bc3044b
    parameters:
    -   alignment_subset_size: 1000
    -   placement_subset_size: 5000
    -   threads: 1
    -   debug: false
    output-name: tree

transformers:
    inputs:
        representative_sequences:
        -   from: DNASequencesDirectoryFormat
            to: DNASequencesDirectoryFormat
        reference_database:
        -   from: SeppReferenceDirFmt
            to: SeppReferenceDirFmt
    output:
    -   from: NewickFormat
        to: NewickDirectoryFormat

environment:
    platform: linux-x86_64
    python: |-
        3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)
        [GCC 9.3.0]
    framework:
        version: 2021.2.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2021.2.0|0'
    plugins:
        types:
            version: 2021.2.0
            website: https://github.com/qiime2/q2-types
        fragment-insertion:
            version: 2021.2.0
            website: https://github.com/qiime2/q2-fragment-insertion
            citations:
            - !cite 'plugin|fragment-insertion:2021.2.0|0'
            - !cite 'plugin|fragment-insertion:2021.2.0|1'
            - !cite 'plugin|fragment-insertion:2021.2.0|2'
            - !cite 'plugin|fragment-insertion:2021.2.0|3'
    python-packages:
        zipp: 3.4.0
        xopen: 1.1.0
        widgetsnbextension: 3.5.1
        wheel: 0.36.2
        webencodings: 0.5.1
        wcwidth: 0.2.5
        urllib3: 1.26.3
        unifrac: 0.20.2
        tzlocal: '2.1'
        typing-extensions: 3.7.4.3
        traitlets: 4.3.3
        tornado: '6.1'
        toml: 0.10.2
        threadpoolctl: 2.1.0
        testpath: 0.4.4
        terminado: 0.9.2
        tax2tree: '1.1'
        statsmodels: 0.12.2
        six: 1.15.0
        setuptools: 49.6.0.post20210108
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.11.1
        scipy: 1.5.3
        scikit-learn: 0.23.1
        scikit-bio: 0.5.6
        ruamel-yaml-conda: 0.15.80
        requests: 2.25.1
        qiime2: 2021.2.0
        q2templates: 2021.2.0
        q2cli: 2021.2.0
        q2-vsearch: 2021.2.0
        q2-types: 2021.2.0
        q2-taxa: 2021.2.0
        q2-sample-classifier: 2021.2.0
        q2-quality-filter: 2021.2.0
        q2-quality-control: 2021.2.0
        q2-phylogeny: 2021.2.0
        q2-metadata: 2021.2.0
        q2-longitudinal: 2021.2.0
        q2-gneiss: 2021.2.0
        q2-fragment-insertion: 2021.2.0
        q2-feature-table: 2021.2.0
        q2-feature-classifier: 2021.2.0
        q2-emperor: 2021.2.0
        q2-diversity: 2021.2.0
        q2-diversity-lib: 2021.2.0
        q2-demux: 2021.2.0
        q2-deblur: 2021.2.0
        q2-dada2: 2021.2.0
        q2-cutadapt: 2021.2.0
        q2-composition: 2021.2.0
        q2-alignment: 2021.2.0
        pyzmq: 22.0.3
        PyYAML: 5.4.1
        pytz: '2021.1'
        python-dateutil: 2.8.1
        pytest: 6.2.2
        PySocks: 1.7.1
        pyrsistent: 0.17.3
        pyparsing: 2.4.7
        pyOpenSSL: 20.0.1
        Pygments: 2.8.0
        pycparser: '2.20'
        pycosat: 0.6.3
        py: 1.10.0
        ptyprocess: 0.7.0
        psutil: 5.8.0
        prompt-toolkit: 3.0.16
        prometheus-client: 0.9.0
        pluggy: 0.13.1
        pip: 21.0.1
        Pillow: 8.1.0
        pickleshare: 0.7.5
        pexpect: 4.8.0
        patsy: 0.5.1
        parso: 0.7.1
        pandocfilters: 1.4.2
        pandas: 1.1.5
        packaging: '20.9'
        olefile: '0.46'
        numpy: 1.19.5
        notebook: 6.2.0
        nose: 1.3.7
        networkx: 2.5.1
        nest-asyncio: 1.4.3
        nbformat: 5.1.2
        nbconvert: 6.0.7
        nbclient: 0.5.2
        natsort: 7.1.1
        msgpack: 1.0.2
        more-itertools: 8.7.0
        mistune: 0.8.4
        matplotlib: 3.2.2
        MarkupSafe: 1.1.1
        lz4: 3.1.3
        lockfile: 0.12.2
        kiwisolver: 1.3.1
        jupyterlab-widgets: 1.0.0
        jupyterlab-pygments: 0.1.2
        jupyter-core: 4.7.1
        jupyter-client: 6.1.11
        jsonschema: 3.2.0
        joblib: 1.0.1
        Jinja2: 2.11.3
        jedi: 0.17.2
        isal: 0.5.0
        ipywidgets: 7.6.3
        ipython: 7.16.1
        ipython-genutils: 0.2.0
        ipykernel: 5.5.0
        iow: 1.0.6
        iniconfig: 1.1.1
        importlib-metadata: 3.4.0
        ijson: 3.1.3
        idna: '2.10'
        hdmedians: 0.14.1
        h5py: 3.1.0
        gneiss: 0.4.6
        gemelli: 0.0.8
        future: 0.18.2
        fastcluster: 1.1.26
        entrypoints: '0.3'
        emperor: 1.0.1
        dnaio: 0.5.0
        DendroPy: 4.5.2
        defusedxml: 0.6.0
        decorator: 4.4.2
        deblur: 1.1.0
        dataclasses: '0.7'
        Cython: 0.29.22
        cycler: 0.10.0
        cutadapt: '3.2'
        cryptography: 3.4.4
        conda: 4.10.0
        conda-package-handling: 1.7.3
        click: 7.1.2
        chardet: 4.0.0
        cffi: 1.14.5
        certifi: 2020.12.5
        cached-property: 1.5.1
        CacheControl: 0.12.6
        brotlipy: 0.7.0
        bokeh: 2.2.3
        bleach: 3.3.0
        biom-format: 2.1.10
        bibtexparser: 1.1.0
        backports.functools-lru-cache: 1.6.1
        backcall: 0.2.0
        attrs: 20.3.0
        async-generator: '1.10'
        argon2-cffi: 20.1.0
        tqdm: 4.7.2
